version: '3.9'

services:
  db:
    image: mysql:latest
    ports:
      - "127.0.0.1:3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: todo
       MYSQL_USER: user
       MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lob/mysql
volumes:
  mysql:
